### PR TITLE
Draft: Use channels to sync ristretto tests

### PR DESCRIPTION
**Pull request by gaby**
I noticed recently that the tests for ristretto fail randomly because the expected values is not there, even if we haven't made any changes to the code/tests. Further checking, it seems the issues is caused by using time.Sleep(10000) during the tests which is not reliable.

This PR updates the tests to use channels and synchronization to wait for the expected value to be set in the store before deleting the key and/or checking the result. This eliminates the need for the time.Sleep call, which can make the test slower and less reliable. The test will wait for the expected result or a timeout to occur, and will fail if the timeout occurs before the expected result is available. This can make the test faster and more reliable.

### CODE REVIEW

**Comment by gaby** [comment]
It seems even the official ristretto tests are using time.Sleep for 10 ms.

Source: https://github.com/dgraph-io/ristretto/blob/main/cache_test.go#L357

There's an open PR that may be related to the issue we see in the tests: https://github.com/dgraph-io/ristretto/pull/286

**Comment by gaby** [comment]
In the comments they suggested migrating to https://github.com/outcaste-io/ristretto which fixes the issues from https://github.com/dgraph-io/ristretto/pull/286

**Review by ReneWerner87 — APPROVED** [review]

**Comment by ReneWerner87** [comment]
image
https://github.com/gofiber/storage/actions/runs/4124801449/jobs/7124673103

**Comment by ReneWerner87** [comment]
not 100% stable i think
i run it 3 times and it happens

**Comment by gaby** [comment]
@ReneWerner87 Yeah, even with these changes it's not stable. Thoughts on using the fork https://github.com/outcaste-io/ristretto ?

**Comment by gaby** [comment]
> whats the difference to the main repo?

It has the changes from this PR: https://github.com/dgraph-io/ristretto/pull/286

**Pull request merged**
