### PR TITLE
Correct module name in coherence store, minor README update

### PR DESCRIPTION
**Pull request by tmiddlet2666**
Correction to module name which i missed and minor README update for docker run.

### CODE REVIEW

**Review by gaby — APPROVED** [review]
lgtm

**Comment by tmiddlet2666** [comment]
@ReneWerner87  Are you able to do a new release of the Coherence storage driver when you can to pickup my corrections to the go.mod file?
Thanks

**Comment by gaby** [comment]
> @ReneWerner87 Are you able to do a new release of the Coherence storage driver when you can to pickup my corrections to the go.mod file? Thanks

https://github.com/gofiber/storage/releases/tag/coherence%2Fv1.0.0

**Comment by tmiddlet2666** [comment]
Thanks!

**Pull request merged**
