### PR TITLE
Added ArangoDB support for storage

### PR DESCRIPTION
**Pull request by antoniodipinto**
This PR adds support for using ArangoDB connection inside Storage.

Respecting the format of all the tests from other storage types, everything is fine.
Please comment here if I need to change something

Thank you

### CODE REVIEW

**Comment by hi019** [comment]
We should consider rejecting PR's that add more storage interfaces to this repository, because we will have to maintain all of these implementations for various databases, some of which we have never used. Instead we could do what [gorilla does](https://github.com/gorilla/sessions#store-implementations) and mention third party stores in the README. 

What do you think @Fenny ?

**Comment by antoniodipinto** [comment]
Hi @hi019 no problem. I understand your point, it's fair and right. 
I will create my own repo of this interface because I really use it in my projects. 

Thank you for your answer

**Comment by hi019** [comment]
Ok. I'll leave this PR open until Fenny replies.

**Comment by Fenny** [comment]
I think we can add popular storage providers as long they are implemented right. By any chance we could add a test environment to the workflow?

**Comment by Fenny** [comment]
I will add a workflow test 👍

**Comment by antoniodipinto** [comment]
Thanks @Fenny and  @hi019!

**Pull request merged**
