### PR TITLE
New Storage Driver: Cassandra

### PR DESCRIPTION
**Pull request by aliziyacevik**
Hey guys, this is the continuum of #852 which I accidentally closed and messed up so I opened this.

Thanks for the reviews.

### CODE REVIEW

**Comment by aliziyacevik** [comment]
hi @gaby, I continuously get Initialize Code Ql and Post Initialize CodeQL errors in GitHub while trying to push. could you help me with those ? I looked up online but didn't find really useful stuff.

**Comment by aliziyacevik** [comment]
I guess that did not happen this time. lol.

**Comment by aliziyacevik** [comment]
Hi @gaby, since #852 is closed I opened this.

**Comment by gaby** [comment]
@aliziyacevik Can you update the gosec.yml inside github to exclude cassandra for the root test, and include cassandra at the botton of the file

**Comment by gaby** [comment]
@aliziyacevik Apparently in macos the library uses ipv6 for localhost lookups 😂

https://github.com/gocql/gocql/issues/997

**Comment by aliziyacevik** [comment]
no problem @gaby, I will work on that to  find a solution. thanks for your help.

**Comment by aliziyacevik** [comment]
hi @gaby, right now I'm assuming the GitHub ci/cd doesn't wait for Cassandra to be available on port 9042,  that's why it can't pass the test. what do you think ?

**Comment by gaby** [comment]
> hi @gaby, right now I'm assuming the GitHub ci/cd doesn't wait for Cassandra to be available on port 9042, that's why it can't pass the test. what do you think ?

Let me do some research and i will reply back here

**Comment by gaby** [comment]
@aliziyacevik I dont think there's a way to run it in gh actions. Setting address to 0.0.0.0 causes container to fail. Cassandra doesnt allow using that

**Comment by aliziyacevik** [comment]
@gaby okay, let me also look for a solution

**Comment by mstrYoda** [comment]
Hi @aliziyacevik can you just remove the service definition for cassandra and add a new step that calls docker commands directly like I did for couchbase in [here](https://github.com/mstrYoda/fiber-storage/blob/main/.github/workflows/test-couchbase.yml#L25).

**Comment by aliziyacevik** [comment]
sure @mstrYoda, the first moment I get on my laptop.

**Comment by aliziyacevik** [comment]
I will try @mstrYoda suggests now.

**Comment by gaby** [comment]
@aliziyacevik Are you able to connect to a local `cassandra` instance in your dev env?

**Comment by aliziyacevik** [comment]
Yes

**Comment by gaby** [comment]
> Yes @gaby. I opened both in Docker and in my local. They're both working.

I'm not sure how cassandra work, but can you run a container and only using this Storage driver connect and set/get data? Or did you need to setup CQL files, etc before trying to use the storage driver?

**Comment by mstrYoda** [comment]
@aliziyacevik if you would like to, let's get together and make a quick pair on Go Türkiye/Fiber discord channel?

**Comment by aliziyacevik** [comment]
Sure @mstrYoda.

**Comment by aliziyacevik** [comment]
Let me check it out. @gaby

**Comment by ReneWerner87** [comment]
@aliziyacevik can you refresh your branch with the master

**Comment by aliziyacevik** [comment]
@mstrYoda when can we make a pair ?

**Comment by mstrYoda** [comment]
> @mstrYoda when can we make a pair ? 

Just ping me on discord 👍

**Comment by gaby** [comment]
@aliziyacevik Can you fix the merge conflicts with the gosec.yml ?

**Comment by aliziyacevik** [comment]
@mstrYoda abi naptın bakıyor muyuz buna beraber yayında fixleyeyim mi ben ? başka şeyler de yaparız yayında. tabi hala davetliysem :)

**Comment by mstrYoda** [comment]
> @gaby sure.
> 
> @mstrYoda abi naptın bakıyor muyuz buna beraber yayında yoksa fixleyeyim mi ben şimdi ? başka şeyler de yaparız yayında. tabi hala davetliysem :)

I am writing to you on discord again, lets meet 👍

**Comment by ReneWerner87** [comment]
@mstrYoda any progress ?

**Comment by ReneWerner87** [comment]
@aliziyacevik @mstrYoda friendly ping, thx for the effort

can you update this PR and also check the last hints

**Comment by ReneWerner87** [comment]
@aliziyacevik @mstrYoda friendly ping

**Comment by aliziyacevik** [comment]
> @aliziyacevik @mstrYoda friendly ping

hey @ReneWerner87, Thanks for the reminder and sorry for the such a long delay :(. I will resolve the conflicts.

**Pull request closed without merging**
