### PR TITLE
chore: use testcontainers-go for couchbase and minio

### PR DESCRIPTION
**Pull request by mdelapenya**
- **chore: missing usage of constant**
- **chore: use testcontainers-go module for couchbase in tests**
- **chore: simplify**
- **chore: use testcontainers-go module for minio in tests**

## What does this PR do?
This PR adds testcontainers-go to the Couchbase and Minio modules, updating the current code to be consistent across modules in how the store is created for testing purpose (minio created one container per test suite, instead of per test method).

## Why is it important?
Increase adoption of testcontainers-go for consistency when running the integration tests on contributions.

## Follow-ups
Consider a) running one container per test suite Vs b) one container per test function. While a) is optimal for resource allocation, it can lead to test data polution if tests are not written correctly to create/destroy its data. OTOH b) can lead to have more containers running, but given the type of tests here, I'd say this is meaningless for the current state of the project.

## Summary by CodeRabbit

- **New Features**
	- Introduced environment variables for Couchbase and MinIO to enhance testing infrastructure.
	- Added a new function for setting up a MinIO test storage environment, improving reliability and isolation of tests.

- **Improvements**
	- Streamlined Couchbase and MinIO testing workflows by removing manual setup steps and utilizing pre-defined Docker images.
	- Enhanced error handling in storage setup functions to improve robustness and prevent misleading test results.

- **Refactor**
	- Updated functions for better clarity and maintainability, directly using `testing.TB` type.
	- Simplified test initialization processes across various components.

### CODE REVIEW

**Comment by gaby** [comment]
Based on our policies, this would be a breaking change. We have to discuss it since it bumps the min version of `golang` to 1.21/1.22

**Comment by mdelapenya** [comment]
I found that the Go version is not consistently set across the different stores, that's why I went ahead with the bump, supported by the fact that Go 1.21 is EOL (https://endoflife.date/go):

| Store      | 1.19 | 1.20 | 1.21 | 1.22 | 1.23 |
|--------------|------|------|------|------|------|
| ArangoDB |  ✅ | ✅   | ✅   |      |    |
| Azure Blob |  ✅ | ✅   | ✅   |      |    |
| Badger |  ✅ | ✅   | ✅   |      |    |
| BBolt |  ✅ | ✅   | ✅   |      |    |
| ClickHouse   |      |      | ✅   | ✅   |      |
| CloudflareKV |      |      | ✅   | ✅   |      |
| Coherence    | ✅   | ✅   | ✅   | ✅   |      |
| Couchbase (*before this PR*) |  ✅ | ✅   | ✅   |      |    |
| DynamoDB |  ✅ | ✅   | ✅   |      |    |
| Etcd |  ✅ | ✅   | ✅   |      |    |
| Memcache |  ✅ | ✅   | ✅   |      |    |
| Memory |  ✅ | ✅   | ✅   |      |    |
| Minio |  ✅ | ✅   | ✅   |      |    |
| MockStorage  |      |      | ✅   | ✅   |      |
| MongoDB |  ✅ | ✅   | ✅   |      |    |
| MSSQL |  ✅ | ✅   | ✅   |      |    |
| MySQL |  ✅ | ✅   | ✅   |      |    |
| NATS         |      | ✅   | ✅   | ✅   |      |
| Pebble |  ✅ | ✅   | ✅   |      |    |
| Postgres     |      | ✅   | ✅   | ✅   |      |
| Redis |  ✅ | ✅   | ✅   |      |    |
| Ristretto |  ✅ | ✅   | ✅   |      |    |
| Rueidis      |      | ✅   | ✅   |      |      |
| S3 |  ✅ | ✅   | ✅   |      |    |
| ScyllaDB |    | ✅   | ✅   |      |    |
| SQLite3 |  ✅ | ✅   | ✅   |      |    |


Besides that, I also found similar issues as with clickhouse regarding compilation, and remembered [the comment about bumping the Go version for clickhouse mod file](https://github.com/gofiber/storage/pull/1506#issuecomment-2302001364).

In any case, I'm open to any discussion about this, doing what's best for the project.

Thanks!

**Comment by ReneWerner87** [comment]
thx LGTM
@gaby can you also check

**Comment by ReneWerner87** [comment]
or maybe its not related -> i will retrigger it

**Comment by ReneWerner87** [comment]
strange
s3 is not related to these code changes
image

i triggered the benchmark in the master , lets see, then it is there i will just merge it

**Comment by mdelapenya** [comment]
@ReneWerner87 thanks for this! I'm preparing another batch PR. What Go versions should I use in the CI matrix? I.e. mongodb tests against Go 1.19, 1.20 and 1.21. Should we standardise to use 3 versions (current, current -1 and current -2)?

**Comment by ReneWerner87** [comment]
thank you

with the goversions it is such a thing, can we make the adjustments without changing the golang versions?

each adapter is independent and has its own major version
we only use a multirepo to manage this

unless it is necessary, we want to spare the consumer a major version switch for as long as possible

**Comment by mdelapenya** [comment]
Makes sense, thanks.

I'll update the store tests only, leaving to you the decision of bumping the Go versions based on the special needs for each one.

**Pull request merged**
