### PR TITLE
Support for automerging dependabot PR's

### PR DESCRIPTION
**Pull request by gaby**
* Adds support for auto-merging minor/patch updates triggered by dependabot. 

Reason for this PR is the high-amount of patch PR's being created by dependabot.

The yaml here is taken from: https://github.com/gofiber/recipes/blob/master/.github/workflows/dependabot_automerge.yml

### CODE REVIEW

**Comment by gaby** [comment]
Also can a new release of Storage be minted?

**Comment by ReneWerner87** [comment]
> * Adds support for auto-merging minor/patch updates triggered by dependabot.
> 
> Reason for this PR is the high-amount of patch PR's being created by dependabot.
> 
> The yaml here is taken from: https://github.com/gofiber/recipes/blob/master/.github/workflows/dependabot_automerge.yml

i know we had added it to the reciepe repository, just don't know if it works here

there are no checks in the reciepe repository

don't know if this automerging checks if all unittests etc. are successful

**Comment by gaby** [comment]
@ReneWerner87 I was worried about that too, but their documentation states that it will ONLY auto-merge if the CI/Checks pass.

More information here: https://github.com/dependabot/fetch-metadata#enabling-auto-merge

**Comment by ReneWerner87** [comment]
okay, then lets test it

**Pull request merged**
