### PR TITLE
feat: Add mockstorage implementation

### PR DESCRIPTION
**Pull request by sixcolors**
This pull request adds a new mockstorage implementation for Fiber. The mockstorage is not persistent and is only used for testing purposes. It includes the necessary code changes and tests.

## Summary by CodeRabbit

- **New Features**
  - Introduced a mock storage implementation for the Fiber framework, allowing users to test storage operations with custom functions.
  - Added configuration options for the mock storage, including default settings and custom function handling.
  - Updated README to include information about the new MockStorage option.

- **Tests**
  - Added comprehensive test cases for various storage operations and custom behaviors in the mock storage implementation.

- **Documentation**
  - Updated documentation to include details about the mock storage implementation and its usage.

### CODE REVIEW

**Review by ReneWerner87 — CHANGES_REQUESTED** [review]
- [x] add release-drafter workflow
- [ ] add dependabot part in config

everything else LGTM

**Comment by gaby** [comment]
@sixcolors Whats the difference with https://github.com/gofiber/storage/tree/main/memory they both use the same underlay structure.

**Comment by sixcolors** [comment]
> @sixcolors Whats the difference with https://github.com/gofiber/storage/tree/main/memory they both use the same underlay structure.

Under the hood mock is an in memory storage. But this is specifically for mocking storage so we can override the functions. Used for writing tests where we want to control storage function returns.

**Comment by ReneWerner87** [comment]
@sixcolors don´t forget to add the workflow for the config
like this
https://github.com/gofiber/storage/blob/main/.github/workflows/release-drafter-arangodb.yml

**Review by ReneWerner87 — APPROVED** [review]

**Comment by ReneWerner87** [comment]
@gaby ok with the PR ?

**Review by gaby — APPROVED** [review]
LGTM

**Pull request merged**
