### PR TITLE
Update Coherence driver to add near cache option

### PR DESCRIPTION
**Pull request by tmiddlet2666**
Updated the version of coherence-go-client and introduced a near-cache option to the storage driver.
Thanks for your review.

## Summary by CodeRabbit

- **New Features**
	- Support for Coherence version 1.22.x and container version updated to 23.09.2.
	- Introduced near cache in the Coherence Go client for caching frequently accessed data locally.
	- Added a `NearCacheTimeout` parameter for configuring the timeout of the near cache.

- **Documentation**
	- Updated Coherence cluster Docker image version details and added information about new features like custom configurations and near cache support.

- **Tests**
	- Added the `-race` flag for enhanced testing in the Go environment.
	- Updated test configurations to include the `NearCacheTimeout` parameter.

### CODE REVIEW

**Comment by tmiddlet2666** [comment]
I've finished my changes. Please let me know if any issues. 
Thanks

**Comment by tmiddlet2666** [comment]
@ReneWerner87 
Please review when you have time.
Thanks

**Review by ReneWerner87 — APPROVED** [review]

**Comment by tmiddlet2666** [comment]
Thanks!

**Comment by tmiddlet2666** [comment]
@ReneWerner87 
Apologies, i found a late breaking issue with v1.1.0 of the coherence-go-client so i released v1.1.1 just today.
Are you able to incorporate this release when depdabot picks it up and create a new coherence storage driver release?
thanks again

**Pull request merged**
