### PR TITLE
s3: New methods: CreateBucket, DeleteBucket, SetWithChecksum.

### LINKED ISSUE #970: 🚀 [Feature]: s3: support setting with checksum
### Feature Description

I understand current s3 implementation is designed for gofiber Storage interface, but it could be used as a s3 library too.

My question is, do you accept PR to add a new function alternative to `Set()` to accept checksum (e.g. sha256)? so that S3 server will verify the data integrity on server side.

Current `Set()` doesn't accept any checksum:

https://github.com/gofiber/storage/blob/main/s3/s3.go#L95C39-L99

The plan is adding new functions to accept checksum like below (since theses functions are not designed for Storage interface, i removed `exp time.Duration`):
```
SetWithChecksumCRC32(key string, val []byte, checksum string)
SetWithChecksumCRC32C(key string, val []byte, checksum string)
SetWithChecksumSHA1(key string, val []byte, checksum string)
SetWithChecksumSHA256(key string, val []byte, checksum string)
```

Or, one function to support all (`checksum map[string]string`, key is checksum algorithm like `CRC32`, `SHA256`, value is the checksum):
```
SetWithChecksum(key string, val []byte, checksum map[string]string)
```

Your opinion?

### Additional Context (optional)

_No response_

### Code Snippet (optional)

_No response_

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my suggestion prior to opening this one.
- [X] I understand that improperly formatted feature requests may be closed without explanation.

### PR DESCRIPTION
**Pull request by iredmail**
- fixes #970 
- [x] New: CreateBucket
- [x] New: DeleteBucket
- [x] New: SetWithChecksum
- [x] Create bucket in unittest instead of GitHub Actions.

### CODE REVIEW

**Comment by ReneWerner87** [comment]
@iredmail thx 
can you add an example in the readme

**Comment by iredmail** [comment]
> can you add an example in the readme

Sure, working on it. But seems GitHub Actions has some problem right now, could you please take a look?

**Comment by ReneWerner87** [comment]
@iredmail pls check 
image

**Review by ReneWerner87 — APPROVED** [review]

**Comment by ReneWerner87** [comment]
@iredmail pls add some description for the new methods and some example to the readme

**Review by gaby — APPROVED** [review]
Only thing missing is the updated docs as suggested above

**Comment by iredmail** [comment]
hi @ReneWerner87 @gaby 

Is it ok now?

**Comment by gaby** [comment]
@iredmail Looks good

**Pull request merged**
